package com.otakuhoarder.mushokufoldtheme;

import android.app.Activity;
import android.app.WallpaperManager;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.LinearGradient;
import android.graphics.Paint;
import android.graphics.Rect;
import android.graphics.Shader;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.io.IOException;

public class MainActivity extends Activity {
    private static final int BG=Color.rgb(8,12,18), PANEL=Color.rgb(17,24,33), GOLD=Color.rgb(202,164,104), TEXT=Color.rgb(241,236,225), MUTED=Color.rgb(166,171,178);
    private final ThemeSpec[] themes={new ThemeSpec("Rudeus","Earth • Wind • Adventure",Color.rgb(133,101,72),Color.rgb(74,132,98)),new ThemeSpec("Roxy","Water Magic • Night Sky",Color.rgb(60,88,145),Color.rgb(92,67,135)),new ThemeSpec("Sylphie","Healing • Forest Light",Color.rgb(74,135,101),Color.rgb(177,201,168)),new ThemeSpec("Eris","Sword • Ember • Resolve",Color.rgb(143,58,54),Color.rgb(202,113,62))};
    private int selectedTheme=0, wallpaperTarget=WallpaperManager.FLAG_SYSTEM|WallpaperManager.FLAG_LOCK; private ThemePreview preview; private TextView selectedLabel; private final Button[] themeButtons=new Button[4];
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);setContentView(buildUi());}
    private View buildUi(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(28));root.setBackgroundColor(BG);scroll.addView(root,new ScrollView.LayoutParams(-1,-2));TextView eyebrow=text("MUSHOKU TENSEI × GALAXY Z FOLD7",12,GOLD,Gravity.CENTER);eyebrow.setLetterSpacing(.12f);root.addView(eyebrow,fullWidth(dp(28)));TextView title=text("A New World on Your Screen",28,TEXT,Gravity.CENTER);title.setTypeface(null,1);root.addView(title,fullWidth(dp(44)));TextView sub=text("Choose a character, preview the artwork, then apply it to Home, Lock, or both.",14,MUTED,Gravity.CENTER);sub.setPadding(dp(8),0,dp(8),dp(14));root.addView(sub,fullWidth(-2));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);for(int i=0;i<4;i++){final int x=i;Button bt=new Button(this);themeButtons[i]=bt;bt.setText(themes[i].name);bt.setAllCaps(false);bt.setTextSize(14);bt.setOnClickListener(v->selectTheme(x));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(52),1);lp.setMargins(dp(3),0,dp(3),0);row.addView(bt,lp);}root.addView(row,fullWidth(dp(58)));selectedLabel=text("",16,TEXT,Gravity.CENTER);selectedLabel.setTypeface(null,1);root.addView(selectedLabel,fullWidth(dp(48)));preview=new ThemePreview();root.addView(preview,fullWidth(dp(360)));TextView at=text("APPLY TO",12,GOLD,Gravity.CENTER);at.setLetterSpacing(.16f);at.setPadding(0,dp(18),0,dp(6));root.addView(at,fullWidth(dp(48)));LinearLayout targets=new LinearLayout(this);targets.setOrientation(LinearLayout.HORIZONTAL);targets.addView(targetButton("Home",WallpaperManager.FLAG_SYSTEM),weighted());targets.addView(targetButton("Lock",WallpaperManager.FLAG_LOCK),weighted());targets.addView(targetButton("Both",WallpaperManager.FLAG_SYSTEM|WallpaperManager.FLAG_LOCK),weighted());root.addView(targets,fullWidth(dp(54)));Button apply=new Button(this);apply.setText("Apply Selected Theme");apply.setAllCaps(false);apply.setTextSize(17);apply.setTextColor(Color.rgb(22,17,11));apply.setTypeface(null,1);apply.setBackground(rounded(GOLD,16,GOLD,0));LinearLayout.LayoutParams alp=fullWidth(dp(58));alp.setMargins(0,dp(14),0,0);root.addView(apply,alp);apply.setOnClickListener(v->applyWallpaper());root.addView(text("v0.3 • Generated character artwork • Fold7 preview",12,Color.rgb(112,119,129),Gravity.CENTER),fullWidth(dp(44)));selectTheme(0);return scroll;}
    private Button targetButton(String s,int t){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setBackground(rounded(PANEL,14,Color.rgb(50,59,71),1));b.setOnClickListener(v->{wallpaperTarget=t;Toast.makeText(this,s+" screen selected",Toast.LENGTH_SHORT).show();});return b;}
    private LinearLayout.LayoutParams weighted(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(50),1);p.setMargins(dp(3),0,dp(3),0);return p;}
    private void selectTheme(int i){selectedTheme=i;ThemeSpec t=themes[i];if(selectedLabel!=null)selectedLabel.setText(t.name+"  •  "+t.tagline);if(preview!=null)preview.invalidate();updateButtons();}
    private void updateButtons(){for(int i=0;i<4;i++){if(themeButtons[i]==null)continue;boolean s=i==selectedTheme;themeButtons[i].setTextColor(s?Color.WHITE:MUTED);themeButtons[i].setBackground(rounded(s?themes[i].primary:PANEL,14,s?GOLD:Color.rgb(46,54,64),s?2:1));}}
    private void applyWallpaper(){try{Bitmap b=createWallpaper(themes[selectedTheme],1800,2400);WallpaperManager.getInstance(this).setBitmap(b,null,true,wallpaperTarget);Toast.makeText(this,themes[selectedTheme].name+" artwork applied",Toast.LENGTH_SHORT).show();}catch(IOException e){Toast.makeText(this,"Could not apply wallpaper: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void drawArtCover(Canvas c,Bitmap art,int l,int t,int r,int b,Paint p){float scale=Math.max((float)(r-l)/art.getWidth(),(float)(b-t)/art.getHeight());int sw=Math.round((r-l)/scale),sh=Math.round((b-t)/scale),sx=Math.max(0,(art.getWidth()-sw)/2),sy=Math.max(0,(art.getHeight()-sh)/2);c.drawBitmap(art,new Rect(sx,sy,Math.min(art.getWidth(),sx+sw),Math.min(art.getHeight(),sy+sh)),new Rect(l,t,r,b),p);}
    private Bitmap createWallpaper(ThemeSpec theme,int w,int h){Bitmap out=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);Bitmap art=GeneratedArt.get(selectedTheme);drawArtCover(c,art,0,0,w,h,p);LinearGradient shade=new LinearGradient(0,h*.45f,0,h,new int[]{Color.TRANSPARENT,Color.argb(190,8,12,18),BG},null,Shader.TileMode.CLAMP);p.setShader(shade);c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.rgb(255,245,220));p.setTextSize(106);p.setTypeface(android.graphics.Typeface.create(android.graphics.Typeface.SERIF,1));c.drawText(theme.name.toUpperCase(),120,h-250,p);p.setTextSize(45);p.setTypeface(android.graphics.Typeface.create(android.graphics.Typeface.SERIF,2));c.drawText(theme.tagline,126,h-175,p);return out;}
    private TextView text(String v,int s,int c,int g){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);t.setGravity(g);return t;}private GradientDrawable rounded(int f,int r,int s,int sw){GradientDrawable g=new GradientDrawable();g.setColor(f);g.setCornerRadius(dp(r));if(sw>0)g.setStroke(dp(sw),s);return g;}private LinearLayout.LayoutParams fullWidth(int h){return new LinearLayout.LayoutParams(-1,h);}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private class ThemePreview extends View{private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);ThemePreview(){super(MainActivity.this);setBackground(rounded(PANEL,22,Color.rgb(55,63,73),1));}@Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();Bitmap art=GeneratedArt.get(selectedTheme);drawArtCover(c,art,dp(6),dp(6),w-dp(6),h-dp(6),p);LinearGradient shade=new LinearGradient(0,h*.45f,0,h,new int[]{Color.TRANSPARENT,Color.argb(205,8,12,18)},null,Shader.TileMode.CLAMP);p.setShader(shade);c.drawRoundRect(dp(6),dp(6),w-dp(6),h-dp(6),dp(20),dp(20),p);p.setShader(null);ThemeSpec t=themes[selectedTheme];p.setColor(Color.WHITE);p.setTextSize(dp(26));p.setTypeface(android.graphics.Typeface.create(android.graphics.Typeface.SERIF,1));c.drawText(t.name,dp(24),h-dp(70),p);p.setTextSize(dp(14));p.setTypeface(null);c.drawText(t.tagline,dp(24),h-dp(43),p);p.setTextSize(dp(11));p.setColor(Color.rgb(230,210,175));c.drawText(w>dp(500)?"UNFOLDED • CHARACTER ART":"COVER • CHARACTER ART",dp(24),h-dp(20),p);}}
    private static class ThemeSpec{final String name,tagline;final int primary,secondary;ThemeSpec(String n,String t,int p,int s){name=n;tagline=t;primary=p;secondary=s;}}
}
